# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fhbasecoat',
                'doc_host': 'https://taya-nicholas.github.io',
                'git_url': 'https://github.com/taya-nicholas/fhbasecoat',
                'lib_path': 'fhbasecoat'},
  'syms': {'fhbasecoat.core': {'fhbasecoat.core.foo': ('core.html#foo', 'fhbasecoat/core.py')}}}
