"""LLM chat components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_chat.ipynb.

# %% auto 0
__all__ = ['ChatInput', 'ChatInterface', 'ChatMessage', 'ChatPrompt', 'ChatAssistant']

# %% ../nbs/03_chat.ipynb 2
from fasthtml.common import *
from .utils import *
from .common import *
from .interactive import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates
from itertools import product
from enum import Enum, auto


# %% ../nbs/03_chat.ipynb 12
def ChatInput(cls="", ta_cls="", width="w-96", **kwargs):
    return Form(
        Textarea(placeholder="Ask, Search or Chat...", cls=f"textarea pr-10 min-h-27 pb-12 {ta_cls} {width}", name="text"),
        Footer(
            Button(Icon("plus"), cls=ButtonT.icon_outline + "rounded-full size-6"
            ),
            Select(
                SelectItem("Sonnet-4.5"),
                SelectItem("Haiku-4.5"),
                SelectItem("Opus-4.5"),
                trigger_btn=ListboxTriggerButton(icon=None, cls=ButtonT.sm_ghost),
                id="model-select", side="top",
            ),
            Div("52% used", cls="text-muted-foreground text-sm ml-auto"),
            Button(Icon("arrow-up"), cls=ButtonT.icon_primary + "rounded-full size-6", **tooltip_kwargs("ctrl+enter"), name="submit-button"),
            cls=f"absolute bottom-0 px-3 pb-3 pt-1.5 flex items-center {width} gap-2"
        ),
        cls=f"relative {cls}",
        **kwargs
    )

# %% ../nbs/03_chat.ipynb 15
def ChatInterface(*contents, chat_input=None, cls="", id=None):
    return Div(
        CardOutline(
            *contents,
            cls="flex flex-col flex-1 m-1 mb-0 p-3 rounded-lg rounded-b-none gap-2",
            id=id,
        ),
        chat_input,
        cls=f"flex flex-col w-full lg:max-w-4xl mx-auto {cls}",
    )

# %% ../nbs/03_chat.ipynb 16
def ChatMessage(content:str, msg_type="", cls="", rounding="", color=""): 
    return Div(
        Div(
            Div(
                P(msg_type, cls="ml-2"), cls=f"text-xs text-muted-foreground border-b border-border hover:cursor-pointer {rounding} rounded-b-none {color}"),
                Div(content, cls="px-4 py-3 whitespace-pre-wrap"),
        ),
        cls=f"border border-border text-sm {cls} {rounding}"
    )

def ChatPrompt(content:str):
    return ChatMessage(content, msg_type="Prompt", cls="bg-card w-[85%]", rounding="rounded-2xl rounded-tl-sm", color="")
    # return ChatMessage(content, msg_type="Prompt", cls="bg-card w-[85%]", rounding="rounded-2xl rounded-tl-sm", color="bg-rose-600/20")

def ChatAssistant(content:str):
    return ChatMessage(content, msg_type="Assistant", cls="bg-background w-[90%] ml-auto mb-2", rounding="rounded-2xl", color="")
    # return ChatMessage(content, msg_type="Assistant", cls="bg-background w-[90%] ml-auto mb-2", rounding="rounded-2xl", color="bg-rose-600/20")

