"""LLM chat components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_chat.ipynb.

# %% auto 0
__all__ = ['ChatInput', 'ChatInterface', 'ChatMessage', 'ChatPrompt', 'ChatAssistant', 'ChatNote', 'CodeHighlightThemeScript',
           'CodeHighlight', 'ChatCode', 'ChatOutput']

# %% ../nbs/03_chat.ipynb 2
from fasthtml.common import *
from .utils import *
from .common import *
from .interactive import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates
from itertools import product
from enum import Enum, auto


# %% ../nbs/03_chat.ipynb 12
def ChatInput(cls="", ta_cls="", width="w-96", **kwargs):
    return Form(
        Textarea(placeholder="Ask, Search or Chat...", cls=f"textarea pr-10 min-h-27 pb-12 {ta_cls} {width}", name="text"),
        Footer(
            Button(Icon("plus"), cls=ButtonT.icon_outline + "rounded-full size-6"
            ),
            Select(
                SelectItem("Sonnet-4.5"),
                SelectItem("Haiku-4.5"),
                SelectItem("Opus-4.5"),
                trigger_btn=ListboxTriggerButton(icon=None, cls=ButtonT.sm_ghost),
                id="model-select", side="top",
            ),
            Div("52% used", cls="text-muted-foreground text-sm ml-auto"),
            Button(Icon("arrow-up"), cls=ButtonT.icon_primary + "rounded-full size-6", **tooltip_kwargs("ctrl+enter"), name="submit-button"),
            cls=f"absolute bottom-0 px-3 pb-3 pt-1.5 flex items-center {width} gap-2"
        ),
        cls=f"relative {cls}",
        **kwargs
    )

# %% ../nbs/03_chat.ipynb 15
def ChatInterface(*contents, chat_input=None, cls="", inner_cls="border-l border-r", id=None):
    return Div(
        Div(
            *contents,
            cls=f"bg-background {inner_cls} flex flex-col flex-1 p-3 gap-3",
            id=id,
        ),
        chat_input,
        cls=f"flex flex-col w-full lg:max-w-4xl mx-auto {cls}",
    )

# %% ../nbs/03_chat.ipynb 16
def ChatMessage(content:str, msg_type="", cls="", rounding="", color="", txt_cls="px-4 py-3 whitespace-pre-wrap"): 
    return Div(
        Div(
            Div(
                P(msg_type, cls="ml-2"), cls=f"text-xs text-muted-background border-b border-border hover:cursor-pointer {rounding} rounded-b-none {color}"),
                Div(content, cls=f"{txt_cls}"),
        ),
        cls=f"border border-border text-sm {cls} {rounding}"
    )

# %% ../nbs/03_chat.ipynb 17
def ChatPrompt(content:str):
    return ChatMessage(content, msg_type="Prompt", cls="bg-card w-[95%]", rounding="rounded-2xl rounded-tl-sm", color="bg-rose-700/70")

# %% ../nbs/03_chat.ipynb 18
def ChatAssistant(content:str):
    return ChatMessage(content, msg_type="Assistant", cls="bg-background w-[90%] ml-auto mb-2", rounding="rounded-2xl", color="bg-rose-700/70")

# %% ../nbs/03_chat.ipynb 19
def ChatNote(content:str):
    return ChatMessage(content, msg_type="Note", cls="bg-card w-[95%] p-0 m-0", rounding="rounded-2xl rounded-tl-sm", color="bg-green-500/50", txt_cls="ml-2 mb-3 mt-1 overflow-auto")

# %% ../nbs/03_chat.ipynb 22
def CodeHighlightThemeScript(
    custom_kws:str # A space separated string of variable names to highlight
):
    return (
        Script(f"""
            function updateHljsTheme() {{
                const isDark = document.documentElement.classList.contains('dark');
                document.getElementById('hljs-light').disabled = isDark;
                document.getElementById('hljs-dark').disabled = !isDark;
            }}
            updateHljsTheme();

            hljs.registerLanguage('python-custom', function(hljs) {{
                var python = hljs.getLanguage('python');
                python.keywords.built_in += ' {custom_kws}';
                return python;
            }});

            document.addEventListener('basecoat:theme', () => setTimeout(updateHljsTheme, 0));
            hljs.highlightAll();
        """),
    )

# %% ../nbs/03_chat.ipynb 23
def CodeHighlight(src):
    return Pre(
        Code(src, cls="language-python-custom text-sm", style="background: transparent; overflow: visible; padding: 0;"),
        cls="m-0 p-0 pt-2 leading-none",
    )

# %% ../nbs/03_chat.ipynb 24
def ChatCode(content:str):
    return ChatMessage(content, msg_type="Code", cls="bg-card w-[95%] p-0 m-0 overflow-hidden", rounding="rounded-2xl rounded-tl-sm", color="bg-blue-500/50", txt_cls="ml-2 pb-2 overflow-auto")

# %% ../nbs/03_chat.ipynb 25
def ChatOutput(content:str):
    return ChatMessage(content, msg_type="Output", cls="bg-card w-[90%] ml-auto p-0 m-0", rounding="rounded-2xl rounded-tl-sm", color="bg-blue-500/50", txt_cls="ml-2 mb-4 overflow-auto")
