"""Complicated components that require more elaborate implementations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_complex.ipynb.

# %% auto 0
__all__ = ['DialogOpenButton', 'DialogCloseButton', 'Dialog', 'AlertDialog']

# %% ../nbs/02_complex.ipynb 3
from fasthtml.common import *
from .utils import *
from .common import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates
from itertools import product
from enum import Enum, auto


# %% ../nbs/02_complex.ipynb 10
def DialogOpenButton(*args, did, cls=ButtonT.outline, **kwargs):
    return Button(*args, onclick=f"document.getElementById('{did}').showModal()", cls=cls, **kwargs)

# %% ../nbs/02_complex.ipynb 12
def DialogCloseButton(content=Icon("x"), cls="", **kwargs):
    return Button(content, onclick="this.closest('dialog').close()", cls=cls, aria_label="Close dialog", **kwargs)

# %% ../nbs/02_complex.ipynb 15
def Dialog(*contents, id, title=None, desc=None, footer=None, close_btn=DialogCloseButton(), cls="w-full sm:max-w-[425px] max-h-[612px]", onclick="if (event.target === this) this.close()", **kwargs):
    parts = []
    if title or desc: parts.append(Header(H2(title), P(desc)))
    parts.append(Section(*contents))
    if footer: parts.append(Footer(footer))
    return fh.Dialog(Div(*parts, close_btn), id=id, cls=f"dialog {cls}", onclick=onclick, **kwargs)

# %% ../nbs/02_complex.ipynb 17
@delegates(Dialog, keep=True)
def AlertDialog(*args, close_btn=None, onclick=None, **kwargs):
    return Dialog(*args, close_btn=close_btn, onclick=onclick, **kwargs)
