"""Interactive components that require more elaborate implementations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_interactive.ipynb.

# %% auto 0
__all__ = ['SelectItem', 'ComboboxItem', 'Separator', 'DialogOpenButton', 'DialogCloseButton', 'Dialog', 'AlertDialog',
           'DropdownTriggerButton', 'DropdownItem', 'Dropdown', 'ListboxTriggerButton', 'SearchBar', 'ListBox',
           'ListboxItem', 'Select', 'Combobox']

# %% ../nbs/02_interactive.ipynb 2
from fasthtml.common import *
from .utils import *
from .common import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates
from itertools import product
from enum import Enum, auto


# %% ../nbs/02_interactive.ipynb 9
def Separator(role="separator", **kwargs):
    return Hr(role=role, **kwargs)

# %% ../nbs/02_interactive.ipynb 12
def DialogOpenButton(*args, did, cls=ButtonT.outline, **kwargs):
    return Button(*args, onclick=f"document.getElementById('{did}').showModal()", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb 14
def DialogCloseButton(content=Icon("x"), cls="", **kwargs):
    return Button(content, onclick="this.closest('dialog').close()", cls=cls, aria_label="Close dialog", **kwargs)

# %% ../nbs/02_interactive.ipynb 17
def Dialog(*contents, id, title=None, desc=None, footer=None, close_btn=DialogCloseButton(), cls="w-full sm:max-w-[425px] max-h-[612px]", onclick="if (event.target === this) this.close()", **kwargs):
    parts = []
    if title or desc: parts.append(Header(H2(title), P(desc)))
    parts.append(Section(*contents))
    if footer: parts.append(Footer(footer))
    return fh.Dialog(Div(*parts, close_btn), id=id, cls=f"dialog {cls}", onclick=onclick, **kwargs)

# %% ../nbs/02_interactive.ipynb 19
@delegates(Dialog, keep=True)
def AlertDialog(*args, close_btn=None, onclick=None, **kwargs):
    return Dialog(*args, close_btn=close_btn, onclick=onclick, **kwargs)

# %% ../nbs/02_interactive.ipynb 23
def DropdownTriggerButton(*contents, did, cls=ButtonT.outline, **kwargs):
    return Button(*contents, id=f"{did}-trigger", aria_haspopup="menu", aria_controls=f"{did}-menu", aria_expanded="false", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb 24
def DropdownItem(*contents, icon=None, shortcut=None, disabled=False, **kwargs):
    parts = []
    if icon: parts.append(icon)
    parts.extend(contents)
    if shortcut: parts.append(Span(shortcut, cls="text-muted-foreground ml-auto text-xs tracking-widest"))
    return Div(*parts, role="menuitem", aria_disabled="true" if disabled else None, **kwargs)

# %% ../nbs/02_interactive.ipynb 25
def Dropdown(*contents, id, btn_content="Open", trigger_btn=None, cls="min-w-65", side="bottom", align="left"):
    """The dropdown menu requires a DropdownTriggerButton to activate. A default version is provided used btn_content value
    but can be overriden by passing a button to the trigger_btn param.
    """ 
    return Div(
        trigger_btn or DropdownTriggerButton(btn_content, did=id),
        Div(
            Div(
                *contents,
                role="menu", id=f"{id}-menu", aria_labelledby=f"{id}-trigger",
            ),
            id=f"{id}-popover", data_popover=True, aria_hidden="true", cls=cls,
            data_side=side, data_align=align,
        ),
        id=id, cls="dropdown-menu"
    )


# %% ../nbs/02_interactive.ipynb 32
def ListboxTriggerButton(
    icon=Icon("chevrons-up-down", cls="text-muted-foreground opacity-50 shrink-0"),
    cls=f"{ButtonT.outline} justify-between font-normal w-[180px]",
    **kwargs
):
    return Button(Span("", cls="truncate"), icon, type="button", aria_haspopup="listbox", aria_expanded="false", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb 33
def SearchBar(value="", placeholder="Search items..."):
    return Header(
        Icon("search"),
        fh.Input(
            type="text", value=value, placeholder=placeholder,
            autocomplete="off", autocorrect="off", spellcheck="false",
            aria_autocomplete="list", role="combobox", 
            aria_expanded="false", 
        )
    )

# %% ../nbs/02_interactive.ipynb 34
def ListBox(*contents, id, trigger_button=ListboxTriggerButton(), search_bar=SearchBar()):
    trigger_button.attrs.update(dict(aria_controls=f"{id}-listbox", id=f"{id}-trigger"))
    if search_bar: search_bar.attrs.update(dict(aria_controls=f"{id}-listbox", aria_labelledby=f"{id}-trigger"))
    return Div(
        trigger_button,
        Div(
            search_bar,
            Div(
                *contents,
                role="listbox", id=f"{id}-listbox", 
                aria_orientation="vertical", 
                aria_labelledby=f"{id}-trigger"
            ),
            id=f"{id}-popover", data_popover=True, aria_hidden="true"
        ),
        Input(type="hidden", name=f"{id}-value", value=""),
        id=id, cls="select"
    )

# %% ../nbs/02_interactive.ipynb 35
def ListboxItem(content, value=None, selected=False, force=False, keywords=None, filter_text=None, disabled=False, **kwargs):
    attrs = {"role": "option", "data_value": value or content}
    if selected: attrs["aria_selected"] = "true"
    if force: attrs["data_force"] = "true"
    if keywords: attrs["data_keywords"] = keywords
    if filter_text: attrs["data_filter"] = filter_text
    if disabled: attrs["aria_disabled"] = "true"
    return Div(content, **attrs, **kwargs)

# %% ../nbs/02_interactive.ipynb 36
# Alias to make the items more discoverable
SelectItem = ComboboxItem = ListboxItem

# %% ../nbs/02_interactive.ipynb 37
@delegates(ListBox, but=["search_bar"])
def Select(*args, searchable=False, **kwargs):
    search_bar = SearchBar() if searchable else None
    return ListBox(*args, search_bar=search_bar, **kwargs)

# %% ../nbs/02_interactive.ipynb 38
@delegates(ListBox, but=["search_bar"])
def Combobox(*args, search_placeholder="Search items...", **kwargs):
    search_bar = SearchBar(placeholder=search_placeholder)
    return ListBox(*args, search_bar=search_bar, **kwargs)
