"""Interactive components that require more elaborate implementations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_interactive.ipynb.

# %% auto 0
__all__ = ['DialogOpenButton', 'DialogCloseButton', 'Dialog', 'AlertDialog', 'DropdownTriggerButton', 'Separator',
           'DropdownHeader', 'DropdownItem', 'Dropdown']

# %% ../nbs/02_interactive.ipynb 2
from fasthtml.common import *
from .utils import *
from .common import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates
from itertools import product
from enum import Enum, auto


# %% ../nbs/02_interactive.ipynb 9
def DialogOpenButton(*args, did, cls=ButtonT.outline, **kwargs):
    return Button(*args, onclick=f"document.getElementById('{did}').showModal()", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb 11
def DialogCloseButton(content=Icon("x"), cls="", **kwargs):
    return Button(content, onclick="this.closest('dialog').close()", cls=cls, aria_label="Close dialog", **kwargs)

# %% ../nbs/02_interactive.ipynb 14
def Dialog(*contents, id, title=None, desc=None, footer=None, close_btn=DialogCloseButton(), cls="w-full sm:max-w-[425px] max-h-[612px]", onclick="if (event.target === this) this.close()", **kwargs):
    parts = []
    if title or desc: parts.append(Header(H2(title), P(desc)))
    parts.append(Section(*contents))
    if footer: parts.append(Footer(footer))
    return fh.Dialog(Div(*parts, close_btn), id=id, cls=f"dialog {cls}", onclick=onclick, **kwargs)

# %% ../nbs/02_interactive.ipynb 16
@delegates(Dialog, keep=True)
def AlertDialog(*args, close_btn=None, onclick=None, **kwargs):
    return Dialog(*args, close_btn=close_btn, onclick=onclick, **kwargs)

# %% ../nbs/02_interactive.ipynb 20
def DropdownTriggerButton(*contents, did, cls=ButtonT.outline, **kwargs):
    return Button(*contents, id=f"{did}-trigger", aria_haspopup="menu", aria_controls=f"{did}-menu", aria_expanded="false", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb 21
def Separator(role="separator", **kwargs):
    return Hr(role=role, **kwargs)

# %% ../nbs/02_interactive.ipynb 22
def DropdownHeader(*contents, **kwargs):
    return Div(*contents, role="heading", **kwargs)

# %% ../nbs/02_interactive.ipynb 23
def DropdownItem(*contents, icon=None, shortcut=None, disabled=False, **kwargs):
    parts = []
    if icon: parts.append(icon)
    parts.extend(contents)
    if shortcut: parts.append(Span(shortcut, cls="text-muted-foreground ml-auto text-xs tracking-widest"))
    return Div(*parts, role="menuitem", aria_disabled="true" if disabled else None, **kwargs)

# %% ../nbs/02_interactive.ipynb 24
def Dropdown(*contents, id, btn_content="Open", trigger_btn=None, cls="min-w-65", side="bottom", align="left"):
    """The dropdown menu requires a DropdownTriggerButton to activate. A default version is provided used btn_content value
    but can be overriden by passing a button to the trigger_btn param.
    """ 
    return Div(
        trigger_btn or DropdownTriggerButton(btn_content, did=id),
        Div(
            Div(
                *contents,
                role="menu", id=f"{id}-menu", aria_labelledby=f"{id}-trigger",
            ),
            id=f"{id}-popover", data_popover=True, aria_hidden="true", cls=cls,
            data_side=side, data_align=align,
        ),
        id=id, cls="dropdown-menu"
    )

