"""App setup and utility functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['slider_script', 'text_css', 'theme_script', 'ss', 'Icon', 'deps', 'basecoat_hdrs', 'p', 'make_hdrs', 'FastHTML',
           'get_preview', 'slugify', 'Window', 'pw', 'VEnum']

# %% ../nbs/00_utils.ipynb 2
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.common import fast_app as ori_fast_app, FastHTML as ori_FastHTML
from fasthtml.jupyter import *
from fastlucide import *
from fastcore.meta import delegates

# %% ../nbs/00_utils.ipynb 4
# Additional script needed for sliders
slider_script = Script("""
const updateSlider = (el) => {
    const min = parseFloat(el.min || 0);
    const max = parseFloat(el.max || 100);
    const value = parseFloat(el.value);
    const percent = (max === min) ? 0 : ((value - min) / (max - min)) * 100;
    el.style.setProperty('--slider-value', `${percent}%`);
};
""")

# %% ../nbs/00_utils.ipynb 5
# For some reason the text tailwind classes are not being properly generated
text_css = Style("""
.text-muted-foreground { color: var(--muted-foreground); }
.text-foreground { color: var(--foreground); }
.hover\\:text-foreground:hover { color: var(--foreground); }
.bg-accent { background-color: var(--accent); }
.bg-border { background-color: var(--border); }
.bg-card { background-color: var(--card); }
.bg-muted { background-color: var(--muted); }
.bg-primary { background-color: var(--primary); }
.bg-background { background-color: var(--background); }
.border-border { border-color: var(--border); }
""")
theme_script = Script("""
(() => {
  const stored = localStorage.getItem('themeMode');
  const dark = stored ? stored === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
  if (dark) document.documentElement.classList.add('dark');
  
  document.addEventListener('basecoat:theme', (e) => {
    const mode = e.detail?.mode || (document.documentElement.classList.contains('dark') ? 'light' : 'dark');
    const isDark = mode === 'dark';
    document.documentElement.classList.toggle('dark', isDark);
    localStorage.setItem('themeMode', isDark ? 'dark' : 'light');
  });
})();
""")

ss = SvgSprites('l-')
Icon = ss # Renaming for more clarity when it is used

deps = {
    'scripts': [
        'https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4',
        'https://cdn.jsdelivr.net/npm/lit@3/dist/index.js',
        'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.6/dist/js/all.min.js'
    ],
    'links': [
        'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.6/dist/basecoat.cdn.min.css'
    ]
}

def make_hdrs(deps):
    scripts = tuple(Script(src=url) for url in deps['scripts'])
    links = tuple(Link(rel='stylesheet', href=url) for url in deps['links'])
    return (theme_script, ss) + scripts + links + (text_css, slider_script)

basecoat_hdrs = make_hdrs(deps)

# %% ../nbs/00_utils.ipynb 7
@delegates(ori_FastHTML, keep=True, but=["pico"])
def FastHTML(hdrs=None, pico=False, **kwargs):
    hdrs = basecoat_hdrs + (hdrs or ())
    return ori_FastHTML(hdrs=hdrs, pico=pico, **kwargs)

# %% ../nbs/00_utils.ipynb 10
def get_preview(app=None): 
    if not app: app = FastHTML(session_cookie="mysession")
    return partial(HTMX, app=app, host=None, port=None)
p = get_preview()

# %% ../nbs/00_utils.ipynb 12
def slugify(s):
    return s.lower().replace(" ", "-")

# %% ../nbs/00_utils.ipynb 14
# To easily preview items in a larger container
def Window(*args, cls="h-96"):
    return Div(*args, cls="w-full flex flex-col items-center justify-center {cls}")

# %% ../nbs/00_utils.ipynb 15
def pw(*args, **kwargs):
    return p(Div(Window(*args, **kwargs), cls="h-100 w-full flex flex-col justify-center items-center"))

# %% ../nbs/00_utils.ipynb 17
class VEnum(Enum):
    def __str__(self): return self.value
    def __add__(self, b): return f"{self.value} {b}"
    def __radd__(self, a): return f"{a} {self.value}"
