# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_aistudio.ipynb.

# %% auto #0
__all__ = ['AIUserMessage']

# %% ../nbs/05_aistudio.ipynb #029cb6bf
from fasthtml.common import *
from .utils import *
from .common import *
from .interactive import *
from fasthtml.jupyter import *
from .md import render_md

# %% ../nbs/05_aistudio.ipynb #251033e0
def AIUserMessage(message:str, user="User", cls_top="text-xs", cls_mid="text-sm"):
    return Div(
        Div(
            Muted(user, cls=cls_top),
            Muted("•", cls=cls_top),
            Muted("5:24 PM", cls=cls_top, **tooltip_kwargs("Apr 14, 5:24 PM")),
            cls="flex gap-2"
        ),
        Div(
            render_md(message),
            cls=f"flex flex-col gap-4 {cls_mid}"
        ),
        cls="flex flex-col border border-transparent hover:border-border rounded-md pt-7 pb-7 pl-3 pr-6 whitespace-pre-wrap gap-2"
    )
