"""LLM chat components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_chat.ipynb.

# %% auto 0
__all__ = ['ChatInput', 'ChatInterface', 'ChatMessage', 'ChatPrompt', 'ChatAssistant', 'ChatNote', 'ChatCode', 'ChatOutput',
           'ChatPromptAndAssistant', 'ChatCodeAndOutput']

# %% ../nbs/04_chat.ipynb 2
from fasthtml.common import *
from .utils import *
from .common import *
from .interactive import *
from .markdown import CodeHighlight
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates
from itertools import product
from enum import Enum, auto


# %% ../nbs/04_chat.ipynb 12
def ChatInput(cls="", ta_cls="", width="w-96", btn_list=None, select_list=None, usage_int=None, placeholder="Ask...", **kwargs):
    select_btn = select_list and Select(
                *map(SelectItem, select_list),
                trigger_btn=ListboxTriggerButton(icon=None, cls=ButtonT.sm_ghost),
                id="model_select", name="model_select", side="top",
            )
    usage_div = usage_int and Div(f"{usage_int}% used", cls="text-muted-foreground text-sm")
    btn_list = btn_list or []
    return Form(
        Textarea(
            placeholder=placeholder, 
            cls=f"textarea pr-10 min-h-27 pb-12 {ta_cls} {width}", 
            name="text",
            onkeydown="if(event.ctrlKey && event.key==='Enter'){event.preventDefault(); this.form.requestSubmit()}",
        ),
        Footer(
            *btn_list,
            select_btn,
            Div(
                usage_div,
                Button(Icon("arrow-up"), cls=ButtonT.icon_primary + "rounded-full size-6", **tooltip_kwargs("ctrl+enter"), name="submit-button"),
                cls="flex ml-auto gap-2 items-center",
            ),
            cls=f"absolute bottom-0 px-3 pb-3 pt-1.5 flex items-center {width} gap-2"
        ),
        cls=f"relative {cls}",
        hx_on__ws_after_send="this.reset()",
        **kwargs
    )

# %% ../nbs/04_chat.ipynb 16
def ChatInterface(*contents, chat_input=None, cls="", inner_cls="border-l border-r overflow-y-auto", id=None):
    return Div(
        Div(
            *contents,
            cls=f"bg-background {inner_cls} flex flex-col flex-1 p-3 gap-3",
            id=id,
        ),
        chat_input,
        cls=f"flex flex-col w-full lg:max-w-4xl mx-auto {cls}",
    )

# %% ../nbs/04_chat.ipynb 17
def ChatMessage(content:str, msg_type="", cls="", rounding="", color="", txt_cls="px-4 py-3 whitespace-pre-wrap"): 
    return Div(
        Div(
            Div(
                P(msg_type, cls="ml-2"), cls=f"text-xs text-muted-background border-b border-border hover:cursor-pointer {rounding} rounded-b-none {color}"),
                Div(content, cls=f"{txt_cls}"),
        ),
        cls=f"border border-border text-sm {cls} {rounding}"
    )

# %% ../nbs/04_chat.ipynb 18
def ChatPrompt(content:str):
    return ChatMessage(content, msg_type="Prompt", cls="bg-card w-[95%]", rounding="rounded-2xl rounded-tl-sm", color="bg-rose-700/70")

# %% ../nbs/04_chat.ipynb 19
def ChatAssistant(content:str):
    return ChatMessage(content, msg_type="Assistant", cls="bg-background w-[90%] ml-auto mb-2", rounding="rounded-2xl", color="bg-rose-700/70")

# %% ../nbs/04_chat.ipynb 20
def ChatNote(content:str):
    return ChatMessage(content, msg_type="Note", cls="bg-card w-[95%] p-0 m-0", rounding="rounded-2xl rounded-tl-sm", color="bg-green-500/50", txt_cls="ml-2 mb-2 mt-1 overflow-auto")

# %% ../nbs/04_chat.ipynb 24
def ChatCode(content:str, highlight=True):
    c = CodeHighlight(content) if highlight else content
    return ChatMessage(c, msg_type="Code", cls="bg-card w-[95%] p-0 m-0 overflow-hidden", rounding="rounded-2xl rounded-tl-sm", color="bg-blue-500/50", txt_cls="ml-2 pb-2 overflow-auto")

# %% ../nbs/04_chat.ipynb 25
def ChatOutput(content:str, highlight=True):
    c = CodeHighlight(content) if highlight else content
    return ChatMessage(c, msg_type="Output", cls="bg-card w-[90%] ml-auto p-0 m-0", rounding="rounded-2xl rounded-tl-sm", color="bg-blue-500/50", txt_cls="ml-2 mb-2 overflow-auto")

# %% ../nbs/04_chat.ipynb 29
def ChatPromptAndAssistant(prompt:str, assistant=None):
    assistant_out = ChatAssistant(assistant) if assistant else assistant
    return Div(
        ChatPrompt(prompt),
        assistant_out,
        cls="flex flex-col gap-2",
    )

# %% ../nbs/04_chat.ipynb 32
def ChatCodeAndOutput(code:str, output=None):
    chat_out = ChatOutput(output) if output else output
    return Div(
        ChatCode(code),
        chat_out,
        cls="flex flex-col gap-2",
    )
