"""LLM chat components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_chat.ipynb.

# %% auto #0
__all__ = ['ChatInput', 'ChatInterface', 'ChatMessage', 'ChatPrompt', 'ChatAssistant', 'ChatNote', 'ChatCode', 'ChatOutput',
           'ChatPromptAndAssistant', 'ChatCodeAndOutput']

# %% ../nbs/04_chat.ipynb #823fd14b
from fasthtml.common import *
from .utils import *
from .common import *
from .interactive import *
from .markdown import CodeHighlight
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates
from itertools import product
from enum import Enum, auto


# %% ../nbs/04_chat.ipynb #859aa474
def ChatInput(cls="", ta_cls="", width="w-96", btn_list=None, select_list=None, usage_int=None, placeholder="Ask...", **kwargs):
    select_btn = select_list and Select(
                *map(SelectItem, select_list),
                trigger_btn=ListboxTriggerButton(icon=None, cls=ButtonT.sm_ghost),
                id="model_select", name="model_select", side="top",
            )
    usage_div = usage_int and Div(f"{usage_int}% used", cls="text-muted-foreground text-sm")
    btn_list = btn_list or []
    return Form(
        Textarea(
            placeholder=placeholder, 
            cls=twm.merge(f"textarea pr-10 min-h-27 pb-12 {ta_cls} {width}"), 
            name="text",
            onkeydown="if(event.ctrlKey && event.key==='Enter'){event.preventDefault(); this.form.requestSubmit()}",
        ),
        Footer(
            *btn_list,
            select_btn,
            Div(
                usage_div,
                Button(Icon("arrow-up"), cls=ButtonT.icon_primary + "rounded-full size-6", **tooltip_kwargs("ctrl+enter"), name="submit-button"),
                cls="flex ml-auto gap-2 items-center",
            ),
            cls=f"absolute bottom-0 px-3 pb-3 pt-1.5 flex items-center {width} gap-2"
        ),
        cls=twm.merge(f"relative {cls}"),
        hx_on__ws_after_send="this.reset()",
        **kwargs
    )

# %% ../nbs/04_chat.ipynb #d32f66e9
def ChatInterface(*contents, chat_input=None, cls="", inner_cls="", id=None):
    return Div(
        Div(
            *contents,
            cls=twm.merge(f"bg-background border-l border-r overflow-y-auto flex flex-col flex-1 p-3 gap-3 {inner_cls}"),
            id=id,
        ),
        chat_input,
        cls=twm.merge(f"flex flex-col w-full lg:max-w-4xl mx-auto {cls}"),
    )

# %% ../nbs/04_chat.ipynb #6e8dab36
def ChatMessage(content:str, msg_type="", cls="", rounding="", color="", txt_cls="px-4 py-3 whitespace-pre-wrap"): 
    return Div(
        Div(
            Div(
                P(msg_type, cls="ml-2"), cls=f"text-xs text-muted-background border-b border-border hover:cursor-pointer {rounding} rounded-b-none {color}"),
                Div(content, cls=f"{txt_cls}"),
        ),
        cls=f"border border-border text-sm {cls} {rounding}"
    )

# %% ../nbs/04_chat.ipynb #80ea3b49
def ChatPrompt(content:str, cls=""):
    return ChatMessage(content, msg_type="Prompt", cls=twm.merge("bg-card w-[95%]", cls), rounding="rounded-2xl rounded-tl-sm", color="bg-rose-700/70")

# %% ../nbs/04_chat.ipynb #5a2e83f1
def ChatAssistant(content:str, cls=""):
    return ChatMessage(content, msg_type="Assistant", cls=twm.merge("bg-background w-[90%] ml-auto mb-2", cls), rounding="rounded-2xl", color="bg-rose-700/70")

# %% ../nbs/04_chat.ipynb #c9fc0499
def ChatNote(content:str, cls=""):
    return ChatMessage(content, msg_type="Note", cls=twm.merge("bg-card w-[95%] p-0 m-0", cls), rounding="rounded-2xl rounded-tl-sm", color="bg-green-500/50", txt_cls="ml-2 mb-2 mt-1 overflow-auto")

# %% ../nbs/04_chat.ipynb #36923f65
def ChatCode(content:str, highlight=True):
    c = CodeHighlight(content) if highlight else content
    return ChatMessage(c, msg_type="Code", cls="bg-card w-[95%] p-0 m-0 overflow-hidden", rounding="rounded-2xl rounded-tl-sm", color="bg-blue-500/50", txt_cls="ml-2 pb-2 overflow-auto")

# %% ../nbs/04_chat.ipynb #903b0d84
def ChatOutput(content:str, highlight=True, cls=""):
    c = CodeHighlight(content) if highlight else content
    return ChatMessage(c, msg_type="Output", cls=twm.merge("bg-card w-[90%] ml-auto p-0 m-0", cls), rounding="rounded-2xl rounded-tl-sm", color="bg-blue-500/50", txt_cls="ml-2 mb-2 overflow-auto")

# %% ../nbs/04_chat.ipynb #66ac5476
def ChatPromptAndAssistant(prompt:str, assistant=None):
    assistant_out = ChatAssistant(assistant) if assistant else assistant
    return Div(
        ChatPrompt(prompt),
        assistant_out,
        cls="flex flex-col gap-2",
    )

# %% ../nbs/04_chat.ipynb #801d92a9
def ChatCodeAndOutput(code:str, output=None):
    chat_out = ChatOutput(output) if output else output
    return Div(
        ChatCode(code),
        chat_out,
        cls="flex flex-col gap-2",
    )
