"""Base/simple components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_common.ipynb.

# %% auto 0
__all__ = ['ButtonT', 'AccordionItem', 'Accordion', 'AlertT', 'Alert', 'Avatar', 'BadgeT', 'Badge', 'accumulate_hrefs',
           'Breadcrumb', 'kebab_to_snakecase', 'mk_cls_enum', 'Button', 'ButtonGroup', 'Card', 'CardOutline',
           'Checkbox', 'Form', 'Kbd', 'Input', 'Label', 'mk_pagination_nums', 'Pagination', 'Progress', 'Radio',
           'RadioGroup', 'SkeletonCircle', 'SkeletonLine', 'SkeletonSquare', 'Slider', 'Spinner', 'Switch',
           'TableFromDict', 'Textarea', 'ThemeSwitcher', 'ToastCloseButton', 'Toaster', 'Toast', 'tooltip_kwargs']

# %% ../nbs/01_common.ipynb 2
from fasthtml.common import *
from .utils import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from itertools import product, accumulate
from enum import Enum, auto


# %% ../nbs/01_common.ipynb 3
# Icon used for dev, spritesheet, when all icons are known/defined
Icon = spritesheet

# %% ../nbs/01_common.ipynb 8
def AccordionItem(title, content, **kwargs):
    return Details(
        Summary(
            H2(
                title,
                Icon("chevron-down", sz=18, cls="text-muted-foreground pointer-events-none size-4 shrink-0 translate-y-0.5 transition-transform duration-200 group-open:rotate-180"),
                cls="flex flex-1 items-start justify-between gap-4 py-4 text-left text-sm font-medium hover:underline"
            ),
            cls="w-full focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] transition-all outline-none rounded-md"
        ),
        Section(
            P(content, cls="text-sm"),
            cls="pb-4"
        ),
        cls="group border-b last:border-b-0",
        **kwargs
    )

def Accordion(*items, **kwargs):
    return Div(
        Section(*items, cls="accordion"),
        **kwargs
    )

# %% ../nbs/01_common.ipynb 12
class AlertT(VEnum):
    default = "alert"
    destructive = "alert-destructive"

# %% ../nbs/01_common.ipynb 13
def Alert(title=None, description=None, icon=None, cls=AlertT.default, **kwargs):
    content = []
    if icon: content.append(icon)
    if title: content.append(H2(title))
    if description: content.append(Section(description))
    return Div(*content, cls=cls, **kwargs)

# %% ../nbs/01_common.ipynb 17
def Avatar(src:str, cls="", **kwargs):
    return Img(src=src, cls=f"size-8 shrink-0 object-cover rounded-full {cls}")

# %% ../nbs/01_common.ipynb 21
class BadgeT(VEnum):
    primary = 'badge-primary'
    secondary = 'badge-secondary'
    destructive = 'badge-destructive'
    outline = 'badge-outline'

def Badge(*args, cls=BadgeT.primary, **kwargs):
    return Span(*args, cls=cls, **kwargs)

# %% ../nbs/01_common.ipynb 25
def accumulate_hrefs(links:list):
    slugs = [slugify(o) for o in links]
    return list(accumulate(slugs, lambda a, b: f"{a}/{b}", initial=""))[1:]

# %% ../nbs/01_common.ipynb 27
def Breadcrumb(links:list, hrefs=None):
    if not hrefs: hrefs = accumulate_hrefs(links)
    contents = []
    for link, href in zip(links[:-1], hrefs):
        contents.append(Li(A(link, href=href, cls="hover:text-foreground transition-colors")))
        contents.append(Li(Icon("chevron-right", cls="size-3.5")))
    contents.append(Li(Span(links[-1], cls="text-foreground font-normal")))

    return Ol(
        *contents,
        cls="text-muted-foreground flex flex-wrap items-center gap-1.5 text-sm break-words sm:gap-2.5",
    )


# %% ../nbs/01_common.ipynb 31
def kebab_to_snakecase(s, strip_s=""): return s.lstrip(strip_s).replace("-", "_")

# %% ../nbs/01_common.ipynb 33
def mk_cls_enum(enum_name, base, variants, modifiers, sizes):
    members = {}
    for sz, mod, var in product(sizes, modifiers, variants):
        val = f"{base}{sz}{mod}{var}"
        nm = kebab_to_snakecase(val, strip_s="-btn")
        members[nm] = val
    return VEnum(enum_name, members)

# %% ../nbs/01_common.ipynb 34
ButtonT = mk_cls_enum(
    "ButtonT", 
    "btn", 
    variants=["primary", "secondary", "destructive", "outline", "ghost", "link"], 
    modifiers=["", "icon-"], 
    sizes=["-", "-sm-", "-lg-"],
)

# %% ../nbs/01_common.ipynb 36
def Button(*args, cls=ButtonT.primary, **kwargs):
    return fh.Button(*args, cls=cls, **kwargs)

# %% ../nbs/01_common.ipynb 40
def ButtonGroup(*args, cls="", **kwargs):
    return Div(*args, role="group", cls=f"button-group {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 44
def Card(*contents, title=None, desc=None, footer=None, cls="", **kwargs):
    parts = []
    if title or desc: parts.append(Header(H2(title), P(desc)))
    parts.append(Section(*contents))
    if footer: parts.append(Footer(footer))
    return Div(
        *parts,
        cls=f"card {cls}",
        **kwargs
    )

# %% ../nbs/01_common.ipynb 45
def CardOutline(*contents, cls="", **kwargs):
    return Div(*contents, cls=f"bg-background border border-border {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 51
def Checkbox(*args, cls="", **kwargs):
    return Input(type="checkbox", cls=f"input {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 55
def Form(*args, cls="", **kwargs):
    return fh.Form(args, cls=f"form {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 59
def Kbd(*args, cls="", **kwargs):
    return fh.Kbd(*args, cls=f"kbd {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 63
def Input(*args, cls="", **kwargs):
    return fh.Input(*args, cls=f"input {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 65
def Label(*args, cls="", **kwargs):
    return fh.Label(*args, cls=f"label {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 70
def mk_pagination_nums(current_page, total_pages, max_side):
    n_list = list(range(max(current_page - max_side, 1), min(current_page + max_side + 1, total_pages+1)))
    if n_list[1] != 2: n_list[1] = "..."
    if n_list[-2] != total_pages-1: n_list[-2] = "..."
    n_list[0] = 1
    n_list[-1] = total_pages
    return n_list

# %% ../nbs/01_common.ipynb 72
def Pagination(current_page, total_pages, max_side=5, href_pattern="/page/{n}"):
    contents = [Li(A(Icon("chevron-left"), " Previous", href=href_pattern.format(n=max(current_page-1, 1)), cls=ButtonT.ghost))]
    for n in mk_pagination_nums(current_page, total_pages, max_side):
        if n == "...":
            contents.append(Li(Div(Icon("ellipsis", cls="size-4 shrink-0"), cls="size-9 flex items-center justify-center")))
        else:
            cls = ButtonT.icon_outline if n == current_page else ButtonT.icon_ghost
            contents.append(Li(A(n, href=href_pattern.format(n=n), cls=cls)))
    contents.append(Li(A("Next ", Icon("chevron-right"), href=href_pattern.format(n=min(current_page+1, total_pages)), cls=ButtonT.ghost)))
    return Nav(Ul(*contents, cls="flex flex-row items-center gap-1"), role="navigation", aria_label="pagination")

# %% ../nbs/01_common.ipynb 76
def Progress(value=0, cls="", **kwargs):
    return Div(
        Div(style=f"width: {value}%", cls="bg-primary h-full w-full flex-1 transition-all"),
        cls=f"bg-primary/20 relative h-2 w-full overflow-hidden rounded-full {cls}",
        **kwargs
    )

# %% ../nbs/01_common.ipynb 80
def Radio(name, value=None, **kwargs):
    if not value: value = name.lower()
    return Label(Input(type="radio", name="radio-group", value=value, **kwargs), name, cls="label")

# %% ../nbs/01_common.ipynb 82
def RadioGroup(*radios, cls="", **kwargs):
    return Fieldset(*radios, cls=f"grid gap-3 {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 86
def SkeletonCircle(cls="size-10", **kwargs):
    return Div(cls=f"bg-accent animate-pulse rounded-full shrink-0 {cls}", **kwargs)

def SkeletonLine(cls="w-full", **kwargs):
    return Div(cls=f"bg-accent animate-pulse rounded-md h-4 {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 87
def SkeletonSquare(cls="size-10", **kwargs):
    return Div(cls=f"bg-accent animate-pulse rounded-md shrink-0 {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 94
def Slider(min="0", max="100", value="50", cls="", **kwargs):
    return Div(
        Input(type="range", cls=f"input {cls}", min=min, max=max, value=value, **kwargs),
        Script("""
            (() => {
                const el = document.currentScript.previousElementSibling;
                updateSlider(el);
                el.addEventListener('input', () => updateSlider(el));
            })();
        """)
    )

# %% ../nbs/01_common.ipynb 98
def Spinner(cls="", **kwargs):
    return Icon("loader-circle", cls=f"animate-spin {cls}", **kwargs)

# %% ../nbs/01_common.ipynb 102
def Switch(*args, **kwargs):
    return Input(*args, type="checkbox", role="switch", cls="input", **kwargs)

# %% ../nbs/01_common.ipynb 106
def TableFromDict(table_dict:dict, caption=None):
    heads = [Th(o) for o in table_dict.keys()]
    rows = [Tr(*[Td(val) for val in row]) for row in zip(*table_dict.values())]
    return Table(
        Caption(caption),
        Thead(Tr(*heads)),
        Tbody(*rows),
        cls="table",
    )

# %% ../nbs/01_common.ipynb 110
def Textarea(*args, placeholder="", cls="", invalid="false", **kwargs):
    return fh.Textarea(*args, placeholder=placeholder, cls=f"textarea {cls}", aria_invalid=invalid, **kwargs)

# %% ../nbs/01_common.ipynb 114
def ThemeSwitcher(cls="", **kwargs):
    return Button(
        Span(Icon("sun"), cls="hidden dark:block"),
        Span(Icon("moon"), cls="block dark:hidden"),
        type="button",
        data_side="bottom", onclick="document.dispatchEvent(new CustomEvent('basecoat:theme'))",
        cls=ButtonT.icon_outline + f"size-8 {cls}"
    )

# %% ../nbs/01_common.ipynb 118
def ToastCloseButton(text="Dismiss"):
    return Button(text, data_toast_action=True, cls=ButtonT.primary)

# %% ../nbs/01_common.ipynb 119
def Toaster(data_align="end"):
    "data_align accepts: ['start', 'center', end']"
    return Div(id="toaster", cls="toaster", data_align=data_align)

# %% ../nbs/01_common.ipynb 120
def Toast(title, desc, icon=Icon("circle-check"), footer=ToastCloseButton(), cls="", role="status", data_category="success", aria_atomic="true", aria_hidden="false", **kwargs):
    return Div(
        Div(icon, Section(H2(title), P(desc)), Footer(footer), cls="toast-content"),
        cls=f"toast {cls}",
        role=role,
        aria_atomic=aria_atomic,
        aria_hidden=aria_hidden,
        data_category=data_category,
        **kwargs
    )

# %% ../nbs/01_common.ipynb 126
def tooltip_kwargs(
    text:str,      # The text to display
    side="top",    # either 'top', 'bottom', 'left', or 'right'
    align="center" # either 'start', 'center', or 'end'
):
    return dict(data_tooltip=text, data_side=side, data_align=align) 
