"""Base/simple components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_common.ipynb.

# %% auto #0
__all__ = ['ButtonT', 'AccordionItem', 'Accordion', 'AlertT', 'Alert', 'Avatar', 'BadgeT', 'Badge', 'accumulate_hrefs',
           'Breadcrumb', 'kebab_to_snakecase', 'mk_cls_enum', 'Button', 'ButtonGroup', 'Card', 'CardOutline',
           'Checkbox', 'Form', 'Kbd', 'Input', 'Label', 'mk_pagination_nums', 'Pagination', 'Progress', 'Radio',
           'RadioGroup', 'SkeletonCircle', 'SkeletonLine', 'SkeletonSquare', 'Slider', 'Spinner', 'Switch',
           'TableFromDict', 'Textarea', 'ThemeSwitcher', 'ToastCloseButton', 'Toaster', 'Toast', 'tooltip_kwargs']

# %% ../nbs/01_common.ipynb #8b990d66
from fasthtml.common import *
from .utils import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from itertools import product, accumulate
from enum import Enum, auto


# %% ../nbs/01_common.ipynb #1c4df537
# Icon used for dev, spritesheet, when all icons are known/defined
Icon = spritesheet

# %% ../nbs/01_common.ipynb #e6593dd0
def AccordionItem(title, content, cls="", icon_cls="", h_cls="", icon=partial(Icon, "chevron-down"), **kwargs):
    icon_css = twm.merge("text-muted-foreground pointer-events-none size-4 shrink-0 translate-y-0.5 transition-transform duration-200 group-open:rotate-180", icon_cls)
    h_css = twm.merge("flex flex-1 items-start justify-between gap-4 py-4 text-left text-sm font-medium hover:underline", h_cls)
    details_css = twm.merge("group border-b last:border-b-0", cls)
    return Details(
        Summary(
            H2(
                title,
                icon(cls=icon_css),
                cls=h_css,
            ),
            cls="w-full focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] transition-all outline-none rounded-md"
        ),
        Section(
            Div(content, cls="text-sm"),
            cls="pb-4"
        ),
        cls=details_css,
        **kwargs
    )

def Accordion(*items, **kwargs):
    return Div(
        Section(*items, cls="accordion"),
        **kwargs
    )

# %% ../nbs/01_common.ipynb #d897eed8
class AlertT(VEnum):
    default = "alert"
    destructive = "alert-destructive"

# %% ../nbs/01_common.ipynb #f90374e6
def Alert(title=None, description=None, icon=None, cls=AlertT.default, **kwargs):
    content = []
    if icon: content.append(icon)
    if title: content.append(H2(title))
    if description: content.append(Section(description))
    return Div(*content, cls=cls, **kwargs)

# %% ../nbs/01_common.ipynb #f3537aa7
def Avatar(src:str, cls="", **kwargs):
    return Img(src=src, cls=twm.merge("size-8 shrink-0 object-cover rounded-full", cls))


# %% ../nbs/01_common.ipynb #abe6a3e0
class BadgeT(VEnum):
    primary = 'badge-primary'
    secondary = 'badge-secondary'
    destructive = 'badge-destructive'
    outline = 'badge-outline'

def Badge(*args, cls=BadgeT.primary, **kwargs):
    return Span(*args, cls=cls, **kwargs)

twm.add_rule("badge_variant", ["badge-primary", "badge-secondary", "badge-destructive", "badge-outline"])

# %% ../nbs/01_common.ipynb #7a643172
def accumulate_hrefs(links:list):
    slugs = [slugify(o) for o in links]
    return list(accumulate(slugs, lambda a, b: f"{a}/{b}", initial=""))[1:]

# %% ../nbs/01_common.ipynb #c17476fb
def Breadcrumb(links:list, hrefs=None, icon=partial(Icon, "chevron-right", cls="size-3.5"), cls=""):
    if not hrefs: hrefs = accumulate_hrefs(links)
    contents = []
    for link, href in zip(links[:-1], hrefs):
        contents.append(Li(A(link, href=href, cls="hover:text-foreground transition-colors")))
        contents.append(Li(icon()))
    contents.append(Li(Span(links[-1], cls="text-foreground font-normal")))

    return Ol(
        *contents,
        cls=twm.merge("text-muted-foreground flex flex-wrap items-center gap-1.5 text-sm break-words sm:gap-2.5", cls),
    )


# %% ../nbs/01_common.ipynb #9651a814
def kebab_to_snakecase(s, strip_s=""): return s.lstrip(strip_s).replace("-", "_")

# %% ../nbs/01_common.ipynb #9cf298f5
def mk_cls_enum(enum_name, base, variants, modifiers, sizes):
    members = {}
    for sz, mod, var in product(sizes, modifiers, variants):
        val = f"{base}{sz}{mod}{var}"
        nm = kebab_to_snakecase(val, strip_s="-btn")
        members[nm] = val
    return VEnum(enum_name, members)

# %% ../nbs/01_common.ipynb #b016f599
ButtonT = mk_cls_enum(
    "ButtonT", 
    "btn", 
    variants=["primary", "secondary", "destructive", "outline", "ghost", "link"], 
    modifiers=["", "icon-"], 
    sizes=["-", "-sm-", "-lg-"],
)

twm.add_rule("button_variant", ["btn-"])

# %% ../nbs/01_common.ipynb #19bc603b
def Button(*args, cls=ButtonT.primary, **kwargs):
    return fh.Button(*args, cls=cls, **kwargs)

# %% ../nbs/01_common.ipynb #ff1059df
def ButtonGroup(*args, cls="", **kwargs):
    return Div(*args, role="group", cls=f"button-group {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #48bb7338
def Card(*contents, title=None, desc=None, footer=None, cls="", **kwargs):
    parts = []
    if title or desc: parts.append(Header(H2(title), P(desc)))
    parts.append(Section(*contents))
    if footer: parts.append(Footer(footer))
    return Div(
        *parts,
        cls=f"card {cls}",
        **kwargs
    )

# %% ../nbs/01_common.ipynb #d011bd7d
def CardOutline(*contents, cls="", **kwargs):
    return Div(*contents, cls=twm.merge("bg-background border border-border", cls), **kwargs)

# %% ../nbs/01_common.ipynb #8800aedd
def Checkbox(*args, cls="", **kwargs):
    return Input(type="checkbox", cls=f"input {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #c1e37529
def Form(*args, cls="", **kwargs):
    return fh.Form(args, cls=f"form {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #e67e12f5
def Kbd(*args, cls="", **kwargs):
    return fh.Kbd(*args, cls=f"kbd {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #78ebf565
def Input(*args, cls="", **kwargs):
    return fh.Input(*args, cls=f"input {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #1feaac21
def Label(*args, cls="", **kwargs):
    return fh.Label(*args, cls=f"label {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #1220d6b0
def mk_pagination_nums(current_page, total_pages, max_side):
    n_list = list(range(max(current_page - max_side, 1), min(current_page + max_side + 1, total_pages+1)))
    if n_list[1] != 2: n_list[1] = "..."
    if n_list[-2] != total_pages-1: n_list[-2] = "..."
    n_list[0] = 1
    n_list[-1] = total_pages
    return n_list

# %% ../nbs/01_common.ipynb #299b8811
def Pagination(current_page, total_pages, max_side=5, href_pattern="/page/{n}", cls=""):
    contents = [Li(A(Icon("chevron-left"), " Previous", href=href_pattern.format(n=max(current_page-1, 1)), cls=ButtonT.ghost))]
    for n in mk_pagination_nums(current_page, total_pages, max_side):
        if n == "...":
            contents.append(Li(Div(Icon("ellipsis", cls="size-4 shrink-0"), cls="size-9 flex items-center justify-center")))
        else:
            button_cls = ButtonT.icon_outline if n == current_page else ButtonT.icon_ghost
            contents.append(Li(A(n, href=href_pattern.format(n=n), cls=button_cls)))
    contents.append(Li(A("Next ", Icon("chevron-right"), href=href_pattern.format(n=min(current_page+1, total_pages)), cls=ButtonT.ghost)))
    return Nav(Ul(*contents, cls=twm.merge("flex flex-row items-center gap-1", cls)), role="navigation", aria_label="pagination")


# %% ../nbs/01_common.ipynb #34d7a699
def Progress(value=0, cls="", **kwargs):
    return Div(
        Div(style=f"width: {value}%", cls="bg-primary h-full w-full flex-1 transition-all"),
        cls=twm.merge("bg-primary/20 relative h-2 w-full overflow-hidden rounded-full", cls),
        **kwargs
    )

# %% ../nbs/01_common.ipynb #679e3fcb
def Radio(name, value=None, cls="", **kwargs):
    if not value: value = name.lower()
    return Label(Input(type="radio", name="radio-group", value=value, **kwargs), name, cls=f"label {cls}")

# %% ../nbs/01_common.ipynb #9ffd09cd
def RadioGroup(*radios, cls="", **kwargs):
    return Fieldset(*radios, cls=f"grid gap-3 {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #49716715
def SkeletonCircle(cls="size-10", **kwargs):
    return Div(cls=twm.merge("bg-accent animate-pulse rounded-full shrink-0", cls), **kwargs)

def SkeletonLine(cls="w-full", **kwargs):
    return Div(cls=twm.merge("bg-accent animate-pulse rounded-md h-4", cls), **kwargs)

def SkeletonSquare(cls="size-10", **kwargs):
    return Div(cls=twm.merge("bg-accent animate-pulse rounded-md shrink-0", cls), **kwargs)

# %% ../nbs/01_common.ipynb #e3c2baad
def Slider(min="0", max="100", value="50", cls="", **kwargs):
    return Div(
        Input(type="range", cls=f"input {cls}", min=min, max=max, value=value, **kwargs),
        Script("""
            (() => {
                const el = document.currentScript.previousElementSibling;
                updateSlider(el);
                el.addEventListener('input', () => updateSlider(el));
            })();
        """)
    )

# %% ../nbs/01_common.ipynb #87670533
def Spinner(cls="", **kwargs):
    return Icon("loader-circle", cls=f"animate-spin {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #cc32dafe
def Switch(*args, cls="", **kwargs):
    return Input(*args, type="checkbox", role="switch", cls=f"input {cls}", **kwargs)

# %% ../nbs/01_common.ipynb #5a6b8541
def TableFromDict(table_dict:dict, caption=None, cls=""):
    heads = [Th(o) for o in table_dict.keys()]
    rows = [Tr(*[Td(val) for val in row]) for row in zip(*table_dict.values())]
    return Table(
        Caption(caption),
        Thead(Tr(*heads)),
        Tbody(*rows),
        cls=f"table {cls}",
    )

# %% ../nbs/01_common.ipynb #5c40aeee
def Textarea(*args, placeholder="", cls="", invalid="false", **kwargs):
    return fh.Textarea(*args, placeholder=placeholder, cls=f"textarea {cls}", aria_invalid=invalid, **kwargs)

# %% ../nbs/01_common.ipynb #7e4105ba
def ThemeSwitcher(cls="", **kwargs):
    return Button(
        Span(Icon("sun"), cls="hidden dark:block"),
        Span(Icon("moon"), cls="block dark:hidden"),
        type="button",
        data_side="bottom", onclick="document.dispatchEvent(new CustomEvent('basecoat:theme'))",
        cls=ButtonT.icon_outline + f"size-8 {cls}"
    )

# %% ../nbs/01_common.ipynb #2bc445e9
def ToastCloseButton(text="Dismiss", cls=ButtonT.primary):
    return Button(text, data_toast_action=True, cls=cls)

# %% ../nbs/01_common.ipynb #b2da3988
def Toaster(data_align="end"):
    "data_align accepts: ['start', 'center', end']"
    return Div(id="toaster", cls="toaster", data_align=data_align)

# %% ../nbs/01_common.ipynb #488c1601
def Toast(title, desc, icon=Icon("circle-check"), footer=ToastCloseButton(), cls="", role="status", data_category="success", aria_atomic="true", aria_hidden="false", **kwargs):
    return Div(
        Div(icon, Section(H2(title), P(desc)), Footer(footer), cls="toast-content"),
        cls=f"toast {cls}",
        role=role,
        aria_atomic=aria_atomic,
        aria_hidden=aria_hidden,
        data_category=data_category,
        **kwargs
    )

# %% ../nbs/01_common.ipynb #77e249ca
def tooltip_kwargs(
    text:str,      # The text to display
    side="top",    # either 'top', 'bottom', 'left', or 'right'
    align="center" # either 'start', 'center', or 'end'
):
    return dict(data_tooltip=text, data_side=side, data_align=align) 
