"""Interactive components that require more elaborate implementations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_interactive.ipynb.

# %% auto #0
__all__ = ['SelectItem', 'ComboboxItem', 'CommandItem', 'Separator', 'ItemHeader', 'DialogOpenButton', 'DialogCloseButton',
           'Dialog', 'AlertDialog', 'DropdownTriggerButton', 'DropdownItem', 'Dropdown', 'PopoverTriggerButton',
           'Popover', 'ListboxTriggerButton', 'SearchBar', 'ListBox', 'ListboxItem', 'Select', 'Combobox', 'TabNav',
           'Tabs', 'IconTitle', 'Sidebar', 'Group', 'SidebarGroup', 'SidebarCollapsable', 'ToggleButton',
           'SeparatorVertical', 'CommandDialog', 'CommandSearch', 'CommandGroup', 'CommandScrollable', 'Command']

# %% ../nbs/02_interactive.ipynb #d9582838
from fasthtml.common import *
from .utils import *
from .common import *
import fasthtml.components as fh
from fasthtml.jupyter import *
from fastcore.meta import delegates


# %% ../nbs/02_interactive.ipynb #6be72afb
def Separator(role="separator", **kwargs):
    return Hr(role=role, **kwargs)

# %% ../nbs/02_interactive.ipynb #58bb3d71
def ItemHeader(*contents, **kwargs):
    return Div(*contents, role="heading", **kwargs)

# %% ../nbs/02_interactive.ipynb #84d9930b
def DialogOpenButton(*args, did, cls=ButtonT.outline, **kwargs):
    return Button(*args, onclick=f"document.getElementById('{did}').showModal()", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb #2bc67633
def DialogCloseButton(content=Icon("x"), cls="", **kwargs):
    return Button(content, onclick="this.closest('dialog').close()", cls=cls, aria_label="Close dialog", **kwargs)

# %% ../nbs/02_interactive.ipynb #772ffeed
def Dialog(*contents, id, title=None, desc=None, footer=None, close_btn=DialogCloseButton(), cls="w-full sm:max-w-[425px] max-h-[612px]", onclick="if (event.target === this) this.close()", **kwargs):
    parts = []
    if title or desc: parts.append(Header(H2(title), P(desc)))
    parts.append(Section(*contents))
    if footer: parts.append(Footer(footer))
    return fh.Dialog(Div(*parts, close_btn), id=id, cls=f"dialog {cls}", onclick=onclick, **kwargs)

# %% ../nbs/02_interactive.ipynb #cb471447
@delegates(Dialog, keep=True)
def AlertDialog(*args, close_btn=None, onclick=None, **kwargs):
    return Dialog(*args, close_btn=close_btn, onclick=onclick, **kwargs)

# %% ../nbs/02_interactive.ipynb #97e28c4d
def DropdownTriggerButton(*contents, did, cls=ButtonT.outline, **kwargs):
    return Button(*contents, id=f"{did}-trigger", aria_haspopup="menu", aria_controls=f"{did}-menu", aria_expanded="false", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb #cbafe2b9
def DropdownItem(*contents, icon=None, shortcut=None, disabled=False, **kwargs):
    parts = []
    if icon: parts.append(icon)
    parts.extend(contents)
    if shortcut: parts.append(Span(shortcut, cls="text-muted-foreground ml-auto text-xs tracking-widest"))
    return Div(*parts, role="menuitem", aria_disabled="true" if disabled else None, **kwargs)

# %% ../nbs/02_interactive.ipynb #47da9c6d
def Dropdown(*contents, id, btn_content="Open", trigger_btn=None, cls="min-w-65", side="bottom", align="left"):
    """The dropdown menu requires a DropdownTriggerButton to activate. A default version is provided used btn_content value
    but can be overriden by passing a button to the trigger_btn param.
    """ 
    return Div(
        trigger_btn or DropdownTriggerButton(btn_content, did=id),
        Div(
            Div(
                *contents,
                role="menu", id=f"{id}-menu", aria_labelledby=f"{id}-trigger",
            ),
            id=f"{id}-popover", data_popover=True, aria_hidden="true", cls=cls,
            data_side=side, data_align=align,
        ),
        id=id, cls="dropdown-menu"
    )


# %% ../nbs/02_interactive.ipynb #a92e3f6a
def PopoverTriggerButton(*contents, pid, cls=ButtonT.outline, **kwargs):
    return Button(*contents, id=f"{pid}-trigger", aria_expanded="false", aria_controls=f"{pid}-popover", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb #3011bfd3
def Popover(*contents, id, btn_content="Open popover", trigger_btn=None, cls="w-80", side="bottom", align="center"):
    """The popover requires a PopoverTriggerButton to activate. A default version is provided using btn_content value
    but can be overridden by passing a button to the trigger_btn param.
    """ 
    return Div(
        trigger_btn or PopoverTriggerButton(btn_content, pid=id),
        Div(
            *contents,
            id=f"{id}-popover", data_popover=True, aria_hidden="true", cls=cls,
            data_side=side, data_align=align,
        ),
        id=id, cls="popover"
    )

# %% ../nbs/02_interactive.ipynb #1f6ad16a
def ListboxTriggerButton(
    icon=Icon("chevrons-up-down", cls="text-muted-foreground opacity-50 shrink-0"),
    cls=f"{ButtonT.outline} justify-between font-normal w-[180px]",
    **kwargs
):
    return Button(Span("", cls="truncate"), icon, type="button", aria_haspopup="listbox", aria_expanded="false", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb #7d427c1f
def SearchBar(value="", placeholder="Search items..."):
    return Header(
        Icon("search"),
        fh.Input(
            type="text", value=value, placeholder=placeholder,
            autocomplete="off", autocorrect="off", spellcheck="false",
            aria_autocomplete="list", role="combobox", 
            aria_expanded="false", 
        )
    )

# %% ../nbs/02_interactive.ipynb #bbd88269
def ListBox(*contents, id, name=None, trigger_btn=ListboxTriggerButton(), search_bar=SearchBar(), side="bottom", align="left"):
    trigger_btn.attrs.update(dict(aria_controls=f"{id}-listbox", id=f"{id}-trigger"))
    if search_bar: search_bar.attrs.update(dict(aria_controls=f"{id}-listbox", aria_labelledby=f"{id}-trigger"))
    nm = name or id
    return Div(
        trigger_btn,
        Div(
            search_bar,
            Div(
                *contents,
                role="listbox", id=f"{id}-listbox", 
                aria_orientation="vertical", 
                aria_labelledby=f"{id}-trigger"
            ),
            id=f"{id}-popover", data_popover=True, aria_hidden="true", data_side=side, data_align=align,
        ),
        Input(type="hidden", name=nm, value=""),
        id=id, cls="select"
    )

# %% ../nbs/02_interactive.ipynb #3856cf9d
def ListboxItem(content, value=None, selected=False, force=False, keywords=None, filter_text=None, disabled=False, **kwargs):
    attrs = {"role": "option", "data_value": value or content}
    if selected: attrs["aria_selected"] = "true"
    if force: attrs["data_force"] = "true"
    if keywords: attrs["data_keywords"] = keywords
    if filter_text: attrs["data_filter"] = filter_text
    if disabled: attrs["aria_disabled"] = "true"
    return Div(content, **attrs, **kwargs)

# %% ../nbs/02_interactive.ipynb #9bb0c0d6
# Alias to make the items more discoverable
SelectItem = ComboboxItem = ListboxItem

# %% ../nbs/02_interactive.ipynb #0ebca32f
@delegates(ListBox, but=["search_bar"])
def Select(*args, searchable=False, **kwargs):
    search_bar = SearchBar() if searchable else None
    return ListBox(*args, search_bar=search_bar, **kwargs)

# %% ../nbs/02_interactive.ipynb #3ce72b5d
@delegates(ListBox, but=["search_bar"])
def Combobox(*args, search_placeholder="Search items...", **kwargs):
    search_bar = SearchBar(placeholder=search_placeholder)
    return ListBox(*args, search_bar=search_bar, **kwargs)

# %% ../nbs/02_interactive.ipynb #098801da
def TabNav(nm, id, idx, selected=False):
    return fh.Button(nm, type="button", role="tab", id=f"{id}-tab-{idx}",  aria_controls=f"{id}-panel-{idx}", aria_selected="true" if selected else "false", tabindex="0")

# %% ../nbs/02_interactive.ipynb #edfdc1c6
def Tabs(contents:list, tablist:list, id:str, default_tab=0, orientation="horizontal", cls="w-96", nav_cls="w-fit"):
    nav_items = [TabNav(o, id, idx, selected=(idx==default_tab)) for idx, o in enumerate(tablist)]
    for idx, content in enumerate(contents):
        active_dict = {"aria_selected": "true"} if idx==default_tab else {"aria_selected": "false", "hidden": True}
        content.attrs.update({"role": "tabpanel", "id": f"{id}-panel-{idx}", "aria_labelledby": f"{id}-tab-{idx}", "tabindex": "-1", **active_dict})

    return Div(
        Nav(
            *nav_items,
             role="tablist", aria_orientation=orientation, cls=nav_cls,
        ),
        *contents,
        cls=f"tabs {cls}", id=id,
    )

# %% ../nbs/02_interactive.ipynb #12b618f8
def IconTitle(title:str, icon=None, size=16):
    ico = Icon(icon, sz=size) if icon else None
    return Div(ico, P(title), cls="flex items-center gap-2")

# %% ../nbs/02_interactive.ipynb #8afb9613
def Sidebar(*args, header=None, footer=None, cls="", nav_cls="", **kwargs):
    return Aside(
        Nav(
            header,
            Section(*args, cls="scrollbar", **kwargs),
            footer,
            cls=nav_cls,
        ),
        cls=f"sidebar {cls}",
    )

# %% ../nbs/02_interactive.ipynb #df3f58c0
def Group(title: str, *args, **kwargs):
    return Div(H3(title), *args, role="group", **kwargs)

# %% ../nbs/02_interactive.ipynb #a89bfa2e
def SidebarGroup(title:str, name_list:list, icon_list:list, href_list=None, href_parent=None):
    if not href_list: href_list = list(map(slugify, name_list))
    links = [Li(A(IconTitle(name, icon=ico), href=f"/{slugify(href_parent)}/{href}" if href_parent else href)) for name, href, ico in zip(name_list, href_list, icon_list)]
    return Group(title, Ul(*links))


# %% ../nbs/02_interactive.ipynb #ff2889a4
def SidebarCollapsable(title:str, name_list:list, href_list=None, href_parent=False):
    if not href_list: href_list = list(map(slugify, name_list))
    links = [Li(A(name, href=f"/{slugify(href_parent)}/{href}" if href_parent else href)) for name, href in zip(name_list, href_list)]
    return Ul(Li(Details(Summary(title), Ul(*links))))

# %% ../nbs/02_interactive.ipynb #a3f977bf
def ToggleButton():
    return Button(
        Icon("panel-left"), 
        type="button",
        onclick="document.dispatchEvent(new CustomEvent('basecoat:sidebar'))",
        cls="btn-ghost p-2"
    )

# %% ../nbs/02_interactive.ipynb #81962845
def ListboxTriggerButton(
    icon=Icon("chevrons-up-down", cls="text-muted-foreground opacity-50 shrink-0"),
    cls=f"{ButtonT.outline} justify-between font-normal w-[180px]",
    **kwargs
):
    return Button(Span("", cls="truncate"), icon, type="button", aria_haspopup="listbox", aria_expanded="false", cls=cls, **kwargs)

# %% ../nbs/02_interactive.ipynb #cf19fb6e
def SeparatorVertical(cls="h-4 w-px mr-2"):
    return Hr(role="separtor", cls=f"bg-border {cls}")

# %% ../nbs/02_interactive.ipynb #912da103
# They have the same functionality so adding alias for discoverability
CommandItem = DropdownItem

# %% ../nbs/02_interactive.ipynb #8e758868
def CommandDialog(*contents, id, cls="", **kwargs):
    return fh.Dialog(*contents, id=id, cls=f"command-dialog {cls}", onclick="if (event.target === this) this.close()")

# %% ../nbs/02_interactive.ipynb #9fcf451a
def CommandSearch(icon=Icon("search"), placeholder="Search...", *kwargs):
    return Header(
        Icon("search"),
        fh.Input(
            type="text", placeholder=placeholder, autocomplete="off", autocorrect="off",
            spellcheck="false", aria_autocomplete="list", role="combobox", aria_expanded="true",
        )
    )

# %% ../nbs/02_interactive.ipynb #6fa27d94
def CommandGroup(*args, **kwargs):
    return Div(*args, role="group", **kwargs)

# %% ../nbs/02_interactive.ipynb #6ab18931
def CommandScrollable(*args, direction="vertical", empty_msg="No results found.", cls="", **kwargs):
    return Div(*args, role="menu", data_empty=empty_msg, aira_orientation=direction, cls=f"scrollbar, {cls}", **kwargs)

# %% ../nbs/02_interactive.ipynb #2fe638eb
def Command(*args, cls="", **kwargs):
    return Div(*args, cls=f"command rounded-lg border shadow-md {cls}", **kwargs)
