"""For rich markdown and text rendering"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_markdown.ipynb.

# %% auto 0
__all__ = ['CodeHighlight', 'CopyableCode', 'TextDotHighlight', 'TextPopover', 'split_md', 'md_header', 'extract_codeblock',
           'md_codeblock', 'render_span', 'render_md_item']

# %% ../nbs/03_markdown.ipynb 2
from fasthtml.common import *
from .utils import *
from .common import *
from .interactive import *
from fasthtml.jupyter import *


# %% ../nbs/03_markdown.ipynb 7
def CodeHighlight(src, cls="m-0 p-0 pt-2 leading-none"):
    return Pre(
        Code(src, cls="language-python-custom text-sm", style="background: transparent; overflow: visible; padding: 0;"),
        cls=cls,
    )

# %% ../nbs/03_markdown.ipynb 8
def CopyableCode(code, lang="python"):
    return Div(
        Div(
            Span(lang, cls="text-xs text-muted-foreground px-3 pt-1 pb-1 mb-0 border border-b-0 rounded-t-lg bg-background"),
            cls="flex pl-2 pt-1",
        ),
        Div(
            CodeHighlight(code.strip(), cls="m-3"),
            Button(
                Icon("copy", cls="size-4 copy-icon"),
                Icon("check", cls="size-4 check-icon hidden text-green-500"),
                cls=f"{ButtonT.ghost} absolute top-2 right-2 size-8 p-0",
                onclick="""
                    navigator.clipboard.writeText(this.closest('.relative').querySelector('code').textContent);
                    this.querySelector('.copy-icon').classList.add('hidden');
                    this.querySelector('.check-icon').classList.remove('hidden');
                    setTimeout(() => {
                        this.querySelector('.copy-icon').classList.remove('hidden');
                        this.querySelector('.check-icon').classList.add('hidden');
                    }, 1500);
                """
            ),
            cls="relative border rounded-lg"
        ),
        cls="rounded-lg bg-muted/50 my-2"
    )

# %% ../nbs/03_markdown.ipynb 12
def TextDotHighlight(text, cls="mx-0.5", before_color="bg-blue-500", after_color="bg-blue-500/40"):
    return Span(
        Span(
            text,
            Icon("info", cls="size-3 inline ml-1 text-muted-foreground"),
            cls="relative z-10"
        ),
        cls=f"relative after:content-[''] after:absolute after:w-[4px] after:h-[4px] after:left-1/2 after:-top-1 after:-translate-x-1/2 after:{before_color} after:rounded-lg after:transition-all hover:cursor-pointer hover:after:{after_color} hover:after:w-[calc(100%+10px)] hover:after:h-[calc(100%+10px)] {cls}"
    )

# %% ../nbs/03_markdown.ipynb 16
def TextPopover(content, text, id, side="right", align="center"):
    return Popover(content, id=id, trigger_btn=PopoverTriggerButton(TextDotHighlight(text), pid=id, cls="text"), side=side, align=align)

# %% ../nbs/03_markdown.ipynb 20
def split_md(md):
    return L(re.split(r"(```.*?```|\n)", md, flags=re.DOTALL)).filter(Self.strip())

# %% ../nbs/03_markdown.ipynb 21
def md_header(md_item):
    level = len(md_item) - len(md_item.lstrip("#"))
    sizes = {1: "text-3xl", 2: "text-2xl", 3: "text-xl", 4: "text-lg", 5: "text-base", 6: "text-sm"}
    H = [H1, H2, H3, H4, H5, H6][level - 1]
    return H(md_item.lstrip("# ").strip(), cls=f"{sizes.get(level, 'text-base')} font-bold my-4")

# %% ../nbs/03_markdown.ipynb 22
def extract_codeblock(codeblock):
    code = re.findall(r"```(\w*)(.*)```", codeblock, flags=re.DOTALL)
    return code[0] if code else code

# %% ../nbs/03_markdown.ipynb 25
def md_codeblock(md_item):
    lang, code = extract_codeblock(md_item)
    return CopyableCode(code, lang)

# %% ../nbs/03_markdown.ipynb 26
def render_span(text, replace_map):
    if replace_map is None: replace_map = {}
    pattern = rf"\b({'|'.join(replace_map.keys())})\b"
    parts = [replace_map.get(p, p) for p in re.split(pattern, text) if p]
    return Span(*parts)

# %% ../nbs/03_markdown.ipynb 27
def render_md_item(md_item: str, replace_map=None):
    if md_item.startswith("#"):   return md_header(md_item)
    if md_item.startswith("```"): return md_codeblock(md_item)
    return render_span(md_item, replace_map)
