"""For rich markdown and text rendering

Docs: https://taya-nicholas.github.io/basecampuimarkdown_mistle.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_markdown_mistle.ipynb.

# %% auto #0
__all__ = ['BasecampHtmlRenderer', 'render_md']

# %% ../nbs/03_markdown_mistle.ipynb #b8655e06
from fasthtml.common import *
from .utils import *
from .common import *
from .interactive import *
from fasthtml.jupyter import *
import re
from mistlefoot import ExtendedHtmlRenderer, parse_attrs
from mistletoe import markdown

# %% ../nbs/03_markdown_mistle.ipynb #e5cef903
class BasecampHtmlRenderer(ExtendedHtmlRenderer):
    def render_heading(self, token):
        _heading_classes = {
            1: "text-4xl font-bold tracking-tight",
            2: "text-3xl font-semibold tracking-tight",
            3: "text-2xl font-semibold tracking-tight",
            4: "text-xl font-semibold tracking-tight",
            5: "text-lg font-medium",
            6: "text-base font-medium",
        }

        inner = self.render_inner(token)
        attr_match = re.search(r'\s*\{([^}]+)\}$', inner)
        extra_attrs = ''
        if attr_match:
            extra_attrs = parse_attrs(attr_match.group(0))
            inner = inner[:attr_match.start()]
        cls = _heading_classes.get(token.level, '')
        return f'<h{token.level} class="{cls}"{extra_attrs}>{inner}</h{token.level}>'

    def render_list(self, token):
        if token.start is not None:
            tag = 'ol'
            lst = 'decimal'
            attr = f' start="{token.start}"' if token.start != 1 else ''
        else:
            tag = 'ul'
            lst = 'disc'
            attr = ''
        self._suppress_ptag_stack.append(not token.loose)
        inner = '\n'.join([self.render(child) for child in token.children])
        self._suppress_ptag_stack.pop()
        return f'<{tag} style="list-style-type: {lst}; padding-left: 1.5rem; display: flex; flex-direction: column; gap: 0.1rem;"{attr}>\n{inner}\n</{tag}>'
        
    def render_link(self, token) -> str:
        template = '<a href="{target}"{title} class="text-[rgb(135,169,255)] font-medium">{inner}</a>'
        target = self.escape_url(token.target)
        if token.title:
            title = ' title="{}"'.format(html.escape(token.title))
        else:
            title = ''
        inner = self.render_inner(token)
        return template.format(target=target, title=title, inner=inner)

    def render_auto_link(self, token):
        target = self.escape_url(token.target)
        return f'<a href="{target}" class="text-[rgb(135,169,255)] font-medium">{target}</a>'



# %% ../nbs/03_markdown_mistle.ipynb #78562be5
def render_md(md:str):
    return NotStr(markdown(md, BasecampHtmlRenderer))
