"""App setup and utility functions

Docs: https://taya-nicholas.github.io/basecampuiutils.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto #0
__all__ = ['spritesheet', 'theme_script', 'deps', 'tailwind_inline', 'p', 'twm', 'get_static_headers', 'get_cdn_headers',
           'make_hdrs', 'basecamp_icons', 'FastHTML', 'get_preview', 'slugify', 'Window', 'pw', 'VEnum', 'Icon',
           'Display', 'H1', 'H2', 'H3', 'H4', 'P', 'Lead', 'Large', 'Small', 'Muted', 'Caption']

# %% ../nbs/00_utils.ipynb #8b990d66
from fastcore.utils import *
from fasthtml.common import *
import fasthtml.common as fh
from fasthtml.jupyter import *
from fastlucide.icons import spritesheet
from fastlucide.core import _style_str, sz_attrs
from enum import Enum
from fastcore.meta import delegates
import re
from tailwind_merge import TailwindMerge

# %% ../nbs/00_utils.ipynb #820fde54
# nbdev workaround to expose spritesheet in `__all__`
spritesheet = spritesheet

# %% ../nbs/00_utils.ipynb #53f31b33
# # Additional script needed for sliders
# slider_script = Script("""
# const updateSlider = (el) => {
#     const min = parseFloat(el.min || 0);
#     const max = parseFloat(el.max || 100);
#     const value = parseFloat(el.value);
#     const percent = (max === min) ? 0 : ((value - min) / (max - min)) * 100;
#     el.style.setProperty('--slider-value', `${percent}%`);
# };
# """)
# # For some reason the text tailwind classes are not being properly generated
# text_css = Style("""
# .text-muted-foreground { color: var(--muted-foreground); }
# .text-foreground { color: var(--foreground); }
# .hover\\:text-foreground:hover { color: var(--foreground); }
# .bg-accent { background-color: var(--accent); }
# .bg-border { background-color: var(--border); }
# .bg-card { background-color: var(--card); }
# .bg-muted { background-color: var(--muted); }
# .bg-primary { background-color: var(--primary); }
# .bg-background { background-color: var(--background); }
# .border-border { border-color: var(--border); }
# """)
theme_script = Script("""
(() => {
  const stored = localStorage.getItem('themeMode');
  const dark = stored ? stored === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
  if (dark) document.documentElement.classList.add('dark');
  
  document.addEventListener('basecoat:theme', (e) => {
    const mode = e.detail?.mode || (document.documentElement.classList.contains('dark') ? 'light' : 'dark');
    const isDark = mode === 'dark';
    document.documentElement.classList.toggle('dark', isDark);
    localStorage.setItem('themeMode', isDark ? 'dark' : 'light');
  });
})();
""")

deps = {
    'scripts': [
        'https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4',
        'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.11/dist/js/all.min.js'
        # 'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.6/dist/js/all.min.js'
    ],
    'links': [
        'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.11/dist/basecoat.cdn.min.css'
        # 'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.6/dist/basecoat.cdn.min.css'
    ]
}



# %% ../nbs/00_utils.ipynb #e525eb15
tailwind_inline = Style("""
@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
  --radius: var(--radius);
}
""", type="text/tailwindcss")

# %% ../nbs/00_utils.ipynb #f34941e4
def get_static_headers():
    hdrs = []
    for p in Path("./static").glob("*.js"):
        hdrs.append(Script(src=f"/static/{p.name}"))
    for p in Path("./static").glob("*.css"):
        hdrs.append(Link(rel="stylesheet", href=f"/static/{p.name}"))
    return tuple(hdrs)

# %% ../nbs/00_utils.ipynb #a359d134
def get_cdn_headers():
    scripts = tuple(Script(src=url) for url in deps['scripts'])
    links = tuple(Link(rel='stylesheet', href=url) for url in deps['links'])
    return scripts + links

def make_hdrs(offline=False):
    hdrs = get_static_headers() if offline else get_cdn_headers()
    return (theme_script,) + hdrs + (tailwind_inline,)
    # return (theme_script,) + hdrs + (text_css, slider_script)

# %% ../nbs/00_utils.ipynb #9efc2e00
def basecamp_icons():
    return [
        "chevron-down",
        "chevron-right",
        "chevron-left",
        "circle-alert",
        "arrow-right",
        "arrow-left",
        "ellipsis",
        "loader-circle",
        "sun",
        "moon",
        "circle-check"
    ]


# %% ../nbs/00_utils.ipynb #8dfbb38c
# def code_highlight_headers():
#     return (
#         Link(rel="stylesheet", href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-light.min.css", id="hljs-light"),
#         Link(rel="stylesheet", href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css", id="hljs-dark"),
#         Script(src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js")
#     )

# %% ../nbs/00_utils.ipynb #7f81a2a2
# def CodeHighlightThemeScript(
#     custom_kws:str="" # A space separated string of variable names to highlight
# ):
#     return (
#         Script(f"""
#             function updateHljsTheme() {{
#                 const isDark = document.documentElement.classList.contains('dark');
#                 document.getElementById('hljs-light').disabled = isDark;
#                 document.getElementById('hljs-dark').disabled = !isDark;
#             }}
#             updateHljsTheme();
# 
#             hljs.registerLanguage('python-custom', function(hljs) {{
#                 var python = hljs.getLanguage('python');
#                 python.keywords.built_in += ' {custom_kws}';
#                 return python;
#             }});
# 
#             document.addEventListener('basecoat:theme', () => setTimeout(updateHljsTheme, 0));
#             document.body.addEventListener('htmx:afterSettle', () => {{
#                 hljs.highlightAll();
#             }});
#             hljs.highlightAll();
#         """),
#     )

# %% ../nbs/00_utils.ipynb #8ef47357
@delegates(fh.FastHTML, keep=True, but=["pico"])
def FastHTML(hdrs=None, ftrs=None, icons=[], code_highlight=False, custom_kws="", offline=False, default_hdrs=True, **kwargs):
    hdrs = make_hdrs(offline) + (hdrs or ()) + (spritesheet,)
    # hdrs = (Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4'), start_ui_css, spritesheet)
    # hdrs = (Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4'), spritesheet)
    if offline: default_hdrs = False
    ftrs = ftrs or ()
    # if code_highlight:
    #     hdrs += code_highlight_headers()
    #     ftrs += CodeHighlightThemeScript(custom_kws)
    spritesheet.nms.update(basecamp_icons())
    spritesheet.nms.update(icons)
    return fh.FastHTML(hdrs=hdrs, ftrs=ftrs, pico=False, default_hdrs=default_hdrs, **kwargs)

# %% ../nbs/00_utils.ipynb #4249504e
def get_preview(app=None): 
    if not app: app = FastHTML(session_cookie="mysession")
    return partial(HTMX, app=app, host=None, port=None)
p = get_preview()

# %% ../nbs/00_utils.ipynb #c39c711f
def slugify(s):
    return re.sub(r"[&/\s]+", "-", s).strip("-").lower()

# %% ../nbs/00_utils.ipynb #070ec513
# To easily preview items in a larger container
def Window(*args, cls="h-96"):
    return Div(*args, cls=f"w-full flex flex-col items-center justify-center {cls}")

# %% ../nbs/00_utils.ipynb #be8ede20
def pw(*args, **kwargs):
    return p(Div(Window(*args, **kwargs), cls="h-100 w-full flex flex-col justify-center items-center"))

# %% ../nbs/00_utils.ipynb #67e47996
class VEnum(StrEnum):
    def __str__(self): return self.value
    def __add__(self, b): return f"{self.value} {b}"
    def __radd__(self, a): return f"{a} {self.value}"

# %% ../nbs/00_utils.ipynb #01f9e270
def Icon(nm, sz=24, vbox=24, stroke=None, stroke_width=None, fill=None, cls=""):
    sym = [ft(t, **attrs) for t,attrs in spritesheet.icons[nm]]
    style = _style_str(stroke, fill, stroke_width)
    return Svg(*sym, cls=f"lucide-icon {cls}", style=style, **sz_attrs(sz, vbox))

# %% ../nbs/00_utils.ipynb #32a8e661
twm = TailwindMerge()

# %% ../nbs/00_utils.ipynb #51c80b71
def Display(*args, cls="", **kwargs):
    cls = twm.merge("scroll-m-20 tracking-tight text-balance first:mt-0 text-4xl leading-tight font-extrabold sm:text-5xl lg:text-6xl", cls)
    return fh.Div(*args, cls=cls, **kwargs)

def H1(*args, cls="", **kwargs):
    cls = twm.merge("scroll-m-20 tracking-tight text-balance first:mt-0 text-3xl leading-tight font-extrabold sm:text-4xl lg:text-5xl", cls)
    return fh.H1(*args, cls=cls, **kwargs)

def H2(*args, cls="", **kwargs):
    cls = twm.merge("scroll-m-20 tracking-tight text-balance first:mt-0 border-b pb-2 text-2xl leading-tight font-semibold sm:text-3xl", cls)
    return fh.H2(*args, cls=cls, **kwargs)

def H3(*args, cls="", **kwargs):
    cls = twm.merge("scroll-m-20 tracking-tight text-balance first:mt-0 text-2xl leading-tight font-semibold", cls)
    return fh.H3(*args, cls=cls, **kwargs)

def H4(*args, cls="", **kwargs):
    cls = twm.merge("scroll-m-20 tracking-tight text-balance first:mt-0 text-xl leading-snug font-semibold", cls)
    return fh.H4(*args, cls=cls, **kwargs)

# %% ../nbs/00_utils.ipynb #9b68e5b8
def P(*args, cls="", **kwargs):
    cls = twm.merge("leading-7", cls)
    return fh.P(*args, cls=cls, **kwargs)

def Lead(*args, cls="", **kwargs):
    cls = twm.merge("text-xl text-muted-foreground", cls)
    return fh.P(*args, cls=cls, **kwargs)

def Large(*args, cls="", **kwargs):
    cls = twm.merge("text-lg font-semibold", cls)
    return fh.Div(*args, cls=cls, **kwargs)

def Small(*args, cls="", **kwargs):
    cls = twm.merge("text-sm leading-none font-medium", cls)
    return fh.P(*args, cls=cls, **kwargs)

def Muted(*args, cls="", **kwargs):
    cls = twm.merge("text-sm text-muted-foreground", cls)
    return fh.P(*args, cls=cls, **kwargs)

def Caption(*args, cls="", **kwargs):
    cls = twm.merge("text-xs font-medium tracking-wider text-muted-foreground uppercase", cls)
    return Div(*args, cls=cls, **kwargs)
