"""App setup and utility functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['spritesheet', 'slider_script', 'text_css', 'theme_script', 'deps', 'basecoat_hdrs', 'p', 'make_hdrs',
           'basecamp_icons', 'code_highlight_headers', 'CodeHighlightThemeScript', 'FastHTML', 'get_preview', 'slugify',
           'Window', 'pw', 'VEnum', 'Icon']

# %% ../nbs/00_utils.ipynb 2
from fastcore.utils import *
from fasthtml.common import *
import fasthtml.common as fh
from fasthtml.jupyter import *
from fastlucide.icons import spritesheet
from fastlucide.core import _style_str, sz_attrs
from enum import Enum
from fastcore.meta import delegates
import re

# %% ../nbs/00_utils.ipynb 3
# nbdev workaround to expose spritesheet in `__all__`
spritesheet = spritesheet

# %% ../nbs/00_utils.ipynb 5
# Additional script needed for sliders
slider_script = Script("""
const updateSlider = (el) => {
    const min = parseFloat(el.min || 0);
    const max = parseFloat(el.max || 100);
    const value = parseFloat(el.value);
    const percent = (max === min) ? 0 : ((value - min) / (max - min)) * 100;
    el.style.setProperty('--slider-value', `${percent}%`);
};
""")
# For some reason the text tailwind classes are not being properly generated
text_css = Style("""
.text-muted-foreground { color: var(--muted-foreground); }
.text-foreground { color: var(--foreground); }
.hover\\:text-foreground:hover { color: var(--foreground); }
.bg-accent { background-color: var(--accent); }
.bg-border { background-color: var(--border); }
.bg-card { background-color: var(--card); }
.bg-muted { background-color: var(--muted); }
.bg-primary { background-color: var(--primary); }
.bg-background { background-color: var(--background); }
.border-border { border-color: var(--border); }
""")
theme_script = Script("""
(() => {
  const stored = localStorage.getItem('themeMode');
  const dark = stored ? stored === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
  if (dark) document.documentElement.classList.add('dark');
  
  document.addEventListener('basecoat:theme', (e) => {
    const mode = e.detail?.mode || (document.documentElement.classList.contains('dark') ? 'light' : 'dark');
    const isDark = mode === 'dark';
    document.documentElement.classList.toggle('dark', isDark);
    localStorage.setItem('themeMode', isDark ? 'dark' : 'light');
  });
})();
""")

deps = {
    'scripts': [
        'https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4',
        'https://cdn.jsdelivr.net/npm/lit@3/dist/index.js',
        'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.6/dist/js/all.min.js'
    ],
    'links': [
        'https://cdn.jsdelivr.net/npm/basecoat-css@0.3.6/dist/basecoat.cdn.min.css'
    ]
}

def make_hdrs(deps):
    scripts = tuple(Script(src=url) for url in deps['scripts'])
    links = tuple(Link(rel='stylesheet', href=url) for url in deps['links'])
    return (theme_script,) + scripts + links + (text_css, slider_script)

basecoat_hdrs = make_hdrs(deps)

# %% ../nbs/00_utils.ipynb 6
def basecamp_icons():
    return [
        "chevron-down",
        "chevron-right",
        "chevron-left",
        "circle-alert",
        "arrow-right",
        "arrow-left",
        "ellipsis",
        "loader-circle",
        "sun",
        "moon",
        "circle-check"
    ]


# %% ../nbs/00_utils.ipynb 7
def code_highlight_headers():
    return (
        Link(rel="stylesheet", href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-light.min.css", id="hljs-light"),
        Link(rel="stylesheet", href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css", id="hljs-dark"),
        Script(src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js")
    )

# %% ../nbs/00_utils.ipynb 8
def CodeHighlightThemeScript(
    custom_kws:str="" # A space separated string of variable names to highlight
):
    return (
        Script(f"""
            function updateHljsTheme() {{
                const isDark = document.documentElement.classList.contains('dark');
                document.getElementById('hljs-light').disabled = isDark;
                document.getElementById('hljs-dark').disabled = !isDark;
            }}
            updateHljsTheme();

            hljs.registerLanguage('python-custom', function(hljs) {{
                var python = hljs.getLanguage('python');
                python.keywords.built_in += ' {custom_kws}';
                return python;
            }});

            document.addEventListener('basecoat:theme', () => setTimeout(updateHljsTheme, 0));
            document.body.addEventListener('htmx:afterSettle', () => {{
                hljs.highlightAll();
            }});
            hljs.highlightAll();
        """),
    )

# %% ../nbs/00_utils.ipynb 10
@delegates(fh.FastHTML, keep=True, but=["pico"])
def FastHTML(hdrs=None, ftrs=None, icons=[], code_highlight=True, custom_kws="", **kwargs):
    hdrs = basecoat_hdrs + (hdrs or ()) + (spritesheet,)
    ftrs = ftrs or ()
    if code_highlight:
        hdrs += code_highlight_headers()
        ftrs += CodeHighlightThemeScript(custom_kws)
    spritesheet.nms.update(basecamp_icons())
    spritesheet.nms.update(icons)
    return fh.FastHTML(hdrs=hdrs, ftrs=ftrs, pico=False, **kwargs)

# %% ../nbs/00_utils.ipynb 12
def get_preview(app=None): 
    if not app: app = FastHTML(session_cookie="mysession")
    return partial(HTMX, app=app, host=None, port=None)
p = get_preview()

# %% ../nbs/00_utils.ipynb 14
def slugify(s):
    return re.sub(r"[&/\s]+", "-", s).strip("-").lower()

# %% ../nbs/00_utils.ipynb 16
# To easily preview items in a larger container
def Window(*args, cls="h-96"):
    return Div(*args, cls=f"w-full flex flex-col items-center justify-center {cls}")

# %% ../nbs/00_utils.ipynb 17
def pw(*args, **kwargs):
    return p(Div(Window(*args, **kwargs), cls="h-100 w-full flex flex-col justify-center items-center"))

# %% ../nbs/00_utils.ipynb 19
class VEnum(Enum):
    def __str__(self): return self.value
    def __add__(self, b): return f"{self.value} {b}"
    def __radd__(self, a): return f"{a} {self.value}"

# %% ../nbs/00_utils.ipynb 24
def Icon(nm, sz=24, vbox=24, stroke=None, stroke_width=None, fill=None, cls=""):
    sym = [ft(t, **attrs) for t,attrs in spritesheet.icons[nm]]
    style = _style_str(stroke, fill, stroke_width)
    return Svg(*sym, cls=f"lucide-icon {cls}", style=style, **sz_attrs(sz, vbox))
